apiVersion: v1
kind: ConfigMap
metadata:
  name: mana-food-payment-config
  namespace: default
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  AllowedHosts: "*"
  OrderService__BaseUrl: "http://order-service:8080"
