apiVersion: v1
kind: Secret
metadata:
  name: mana-food-payment-secrets
  namespace: default
type: Opaque
stringData:
  payment_access_token: "REPLACE_WITH_MERCADOPAGO_ACCESS_TOKEN"
  payment_user_id: "REPLACE_WITH_USER_ID"
  payment_external_pos_id: "REPLACE_WITH_EXTERNAL_POS_ID"
  ConnectionStrings__DefaultConnection: "PLACEHOLDER_CONNECTION_STRING"