apiVersion: v1
kind: Service
metadata:
  name: mana-food-payment-service
  namespace: default
  labels:
    app: mana-food-payment
spec:
  selector:
    app: mana-food-payment
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
