<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="FluentAssertions" Version="6.13.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="coverlet.collector" Version="3.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ManaFoodPayment.Application/ManaFoodPayment.Application.csproj" />
    <ProjectReference Include="../../src/ManaFoodPayment.Infrastructure/ManaFoodPayment.Infrastructure.csproj" />
    <ProjectReference Include="../../src/ManaFoodPayment.Domain/ManaFoodPayment.Domain.csproj" />
  </ItemGroup>
</Project>
