name: "CD Deploy to Infra (trigger infra pipeline)"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-payment]

jobs:
  trigger-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mana-food-infra pipeline
        env:
          PERSONAL_ACCESS_TOKEN_MANA_FOOD_APP: ${{ secrets.PERSONAL_ACCESS_TOKEN_MANA_FOOD_APP }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN_MANA_FOOD_APP" \
            https://api.github.com/repos/mana-food/mana-food-infra/actions/workflows/cd-deploy.yml/dispatches \
            -d '{"ref":"main","inputs":{"deploy_mode":"full-deploy"}}'
