name: CI Pull Request
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore src/ManaFoodPayment.sln
      - name: Build
        run: dotnet build --no-restore src/ManaFoodPayment.sln -c Release
      - name: Test
        run: |
          if [ -d "tests" ]; then dotnet test --no-build --verbosity normal; else echo "No tests found"; fi
