name: "[Etapa 4] Análise de Pushes"
on:
  push:
    branches-ignore:
      - main   # ignora pushes na main, só roda nas outras branches

jobs:
  # Steps: Build, Testes e verificação de cobertura de código
  analise-de-pushes:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Rodar Testes e Cobertura
        run: |
          dotnet test --configuration Release --no-build --verbosity normal \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./TestResults/coverage.opencover.xml

      - name: Upload cobertura de código
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-opencover
          path: '**/coverage.opencover.xml'