<<<<<<< HEAD
name: CI Pull Request
=======
name: "[Etapa 1] CI Pull Request"

>>>>>>> main
on:
  pull_request:
    branches: [ "main" ]

jobs:
<<<<<<< HEAD
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore src/ManaFoodPayment.sln
      - name: Build
        run: dotnet build --no-restore src/ManaFoodPayment.sln -c Release
      - name: Test
        run: |
          if [ -d "tests" ]; then dotnet test --no-build --verbosity normal; else echo "No tests found"; fi
=======
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Rodar Testes
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publicar resultados de teste (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults
            **/coverage.opencover.xml
>>>>>>> main
